python -W ignore main.py --colloc_metric PMI --colloc_thresh 5.0 --word_replacer BERTReplacer --keep_case --top_k 3 --score thousand_lines_truecased.xlsx thousand_lines_thresh5.xlsx
@REM python -W ignore main.py --colloc_metric PMI3 --word_replacer BERTReplacer --keep_case --top_k 3 --score thousand_newslines.xlsx thousand_newslines_bert_zero_thresh_top3_scored1.xlsx
@REM python -W ignore main.py --colloc_metric PMI3 --word_replacer BERTReplacer --bert_model_path bert_jokes --top_k 12 --score thousand_newslines.xlsx  thousand_newslines_bert_jokes_zero_thresh_top12_scored.xlsx
@REM python -W ignore main.py --colloc_metric PMI3 --word_replacer GensimCollocateReplacer --keep_case --keep_all --score thousand_newslines.xlsx thousand_newslines_colloc_scored.xlsx
@REM python -W ignore main.py --colloc_metric PMI3 --word_replacer GensimCollocateReplacer --colloc_matrix_path CM_nltk_jokes --keep_case --keep_all --score thousand_newslines.xlsx thousand_newslines_jokecolloc_scored.xlsx
@REM python -W ignore main.py --colloc_metric LL --colloc_thresh 0.5 --word_replacer BERTReplacer --keep_case --top_k 3 --score thousand_newslines.xlsx LL_thousand_newslines_bert_notrash_top3_scored.xlsx
@REM python -W ignore main.py --colloc_metric LL --colloc_thresh 0.5 --word_replacer BERTReplacer --bert_model_path bert_jokes --top_k 12 --score thousand_newslines.xlsx  LL_thousand_newslines_bert_jokes_no_trash_top12_scored.xlsx
@REM python -W ignore main.py --colloc_metric LL --colloc_thresh 0.5 --word_replacer GensimCollocateReplacer --keep_case --keep_all --score thousand_newslines.xlsx LL_thousand_newslines_colloc_scored.xlsx
@REM python -W ignore main.py --colloc_metric LL --colloc_thresh 0.5 --word_replacer GensimCollocateReplacer --colloc_matrix_path CM_nltk_jokes --keep_case --keep_all --score thousand_newslines.xlsx LL_thousand_newslines_jokecolloc_scored.xlsx
@REM python -W ignore main.py --colloc_metric Dice --colloc_thresh 0.3 --word_replacer BERTReplacer --keep_case --top_k 3 --score thousand_newslines.xlsx Dice_thousand_newslines_bert_notrash_top3_scored.xlsx
@REM python -W ignore main.py --colloc_metric Dice --colloc_thresh 0.3 --word_replacer BERTReplacer --bert_model_path bert_jokes --top_k 12 --score thousand_newslines.xlsx  Dice_thousand_newslines_bert_jokes_no_trash_top12_scored.xlsx
@REM python -W ignore main.py --colloc_metric Dice --colloc_thresh 0.3 --word_replacer GensimCollocateReplacer --keep_case --keep_all --score thousand_newslines.xlsx Dice_thousand_newslines_colloc_scored.xlsx
@REM python -W ignore main.py --colloc_metric Dice --colloc_thresh 0.3 --word_replacer GensimCollocateReplacer --colloc_matrix_path CM_nltk_jokes --keep_case --keep_all --score thousand_newslines.xlsx Dice_thousand_newslines_jokecolloc_scored.xlsx
@REM python -W ignore main.py --colloc_metric Jaccard --colloc_thresh 0.3 --word_replacer BERTReplacer --keep_case --top_k 3 --score thousand_newslines.xlsx Jaccard_thousand_newslines_bert_notrash_top3_scored.xlsx
@REM python -W ignore main.py --colloc_metric Jaccard --colloc_thresh 0.3 --word_replacer BERTReplacer --bert_model_path bert_jokes --top_k 12 --score thousand_newslines.xlsx  Jaccard_thousand_newslines_bert_jokes_no_trash_top12_scored.xlsx
@REM python -W ignore main.py --colloc_metric Jaccard --colloc_thresh 0.3 --word_replacer GensimCollocateReplacer --keep_case --keep_all --score thousand_newslines.xlsx Jaccard_thousand_newslines_colloc_scored.xlsx
@REM python -W ignore main.py --colloc_metric Jaccard --colloc_thresh 0.3 --word_replacer GensimCollocateReplacer --colloc_matrix_path CM_nltk_jokes --keep_case --keep_all --score thousand_newslines.xlsx Jaccard_thousand_newslines_jokecolloc_scored.xlsx